### ISSUE TITLE
Editing twice shouldn't show you twice

### ISSUE THREAD

**Issue by BobbieGoede** [Edergoed/deadlines-frontend#2]
if creator == last editor
   show creator only

![](https://i.gyazo.com/a859109226216dfc3d420c81cf308a6c.png)

![](https://i.gyazo.com/451dc93096b0cb63d1c8b6c04af35e8f.png)

**Comment by LiamEderzeel** [comment]
Are you sure that you didn't edit with second profile?, cause it seems to work in the rest of the site.

**Comment by LiamEderzeel** [comment]
Fixed that users gravatar showes dubbel in editor, fixed that undefined gravatar shows up
